import AppKit
import Foundation
import VoinpCore

/// `NSPasteboard` をテスト可能にするための最小の口。
/// 復元の不変条件（changeCount が動いていたら復元しない）は微妙で退行しやすいため、
/// ここだけはテストのためにプロトコルを切る価値がある。
@MainActor
public protocol PasteboardProtocol: AnyObject, Sendable {
    var changeCount: Int { get }
    func clearAndWrite(_ text: String, concealed: Bool) -> Int
    func snapshot() -> [[String: Data]]
    func restore(_ items: [[String: Data]])
}

@MainActor
public final class SystemPasteboard: PasteboardProtocol {
    private let pb: NSPasteboard
    public init(_ pb: NSPasteboard = .general) { self.pb = pb }

    public var changeCount: Int { pb.changeCount }

    public func clearAndWrite(_ text: String, concealed: Bool) -> Int {
        pb.clearContents()
        pb.setString(text, forType: .string)
        if concealed {
            // クリップボード履歴アプリ（Maccy / Paste / Alfred / Raycast）が尊重する
            // 事実上の標準マーカー。4 行でディクテーション結果が履歴を埋めるのを防げる。
            pb.setString("", forType: .init("org.nspasteboard.TransientType"))
            pb.setString("", forType: .init("org.nspasteboard.ConcealedType"))
            pb.setString("", forType: .init("org.nspasteboard.AutoGeneratedType"))
        }
        return pb.changeCount
    }

    public func snapshot() -> [[String: Data]] {
        (pb.pasteboardItems ?? []).map { item in
            var d: [String: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) { d[type.rawValue] = data }
            }
            return d
        }
    }

    public func restore(_ items: [[String: Data]]) {
        pb.clearContents()
        guard !items.isEmpty else { return }
        let objs = items.map { dict -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in dict { item.setData(data, forType: .init(type)) }
            return item
        }
        pb.writeObjects(objs)
    }
}

/// 復元するかどうかの判定。**これがペーストボード周りで唯一保証できる不変条件。**
///
/// 「ペーストが着弾したか」は原理的に検証できない（`changeCount` は読み取りで増えない）。
/// できるのは「自分が書いた後に誰かが書いていたら、その新しい内容を壊さない」ことだけ。
public enum PasteboardRestorePolicy {
    public static func shouldRestore(currentChangeCount: Int, ourChangeCount: Int) -> Bool {
        currentChangeCount == ourChangeCount
    }
}
